export const INPUTS = [
  {
    label: "Name",
    variant: "standard",
    icon: "user",
    helperText: "",
    error: false,
    value: "",
    name: "name",
  },
  {
    label: "Last Name",
    variant: "standard",
    icon: "user",
    helperText: "",
    error: false,
    value: "",
    name: "lastName",
  },
  {
    label: "Email",
    variant: "standard",
    icon: "email",
    helperText: "",
    error: false,
    value: "",
    name: "email",
  },
  {
    label: "12/12/12",
    variant: "standard",
    icon: "calendar",
    helperText: "",
    error: false,
    value: "",
    name: "email",
  },
  {
    label: "Dacodes",
    variant: "standard",
    icon: "portfolio",
    helperText: "",
    error: false,
    value: "",
    name: "email",
  },
  {
    label: "Employes range - less 50",
    variant: "standard",
    helperText: "",
    error: false,
    value: "",
    name: "email",
  },
  {
    label: "Phone",
    variant: "standard",
    icon: "phone",
    helperText: "",
    error: false,
    value: "",
    name: "email",
  },
];
